//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using authenticationAndAuthoraization;
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class stock_management_DBEntities1 : DbContext
{
    public stock_management_DBEntities1()
        : base("name=stock_management_DBEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tblUsers> tblUsers { get; set; }
}
